[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"   # Asegúrate de usar la versión compatible más reciente
tokio = { version = "1", features = ["full"] }


